# Exercise 1 (4 points)

Decision Trees primarily belong to which family of Prescriptive Analytics methods?

- (a) Evolutionary computation
- (b) Logic-based models
- (c) Mathematical programming
- (d) Mathematical programming
- (e) None of the above

B

# Exercise 2 (4 points)

What is the role of Operations Research (OR) in Prescriptive Analytics, and how do the two fields overlap?

rocuses on finding optimal solutions to decision problems using mathematical methods, such as optimization, simulation, and decision analysis. prescriptive uses the same methods to recommend the best course of action, making OR the foundation of many prescriptive analytics techniques.

# Exercise 3 (4 points)

What is the primary goal of Mathematical Programming in Prescriptive Analytics?

- (a) Identifying patterns in large datasets
- (b) Simulating random variables
- (c) Optimizing a function subject to constraints
- (d) Analyzing past events
- (e) All of the above

C

# Exercise 4

Consider the `Bank_Churners.csv` data file. This data file contains information related to credit card customers of some bank. This is a brief description of the data:

- `CLIENTNUM` : Client number. Unique identifier for the customer holding the account
- `Attrition_Flag` : Internal event (customer activity) variable - if the account is closed then 1 else 0
- `Customer_Age` : Demographic variable - Customer's Age in Years
- `Gender` : M=Male, F=Female
- `Dependent_count` : Number of dependents
- `Education_Level` : Educational Qualification of the account holder (example: high school, college graduate, etc.)
- `Marital_Status` : Married, Single, Divorced, Unknown
- `Income_Category` : Annual Income Category of the account holder < $40K, $40K - 60K, $60K - $80K, $80K-$120K
- `Card_Category` : Product Variable - Type of Card (Blue, Silver, Gold, Platinum)
- `Months_on_book` : Period of relationship with bank
- `Total_Relationship_count` : Total no. of products held by the customer
- `Months_Inactive_12_mon` : No. of months inactive in the last 12 months
- `Contacts_Count_12_mon` : No. of Contacts in the last 12 months
- `Credit_Limit` : Credit Limit on the Credit Card
- `Total_Revolving_Bal` : Total Revolving Balance on the Credit Card
- `Avg_Open_To_Buy` : Open to Buy Credit Line (Average of last 12 months)
- `Total_Amt_Chng_Q4_Q1` : Change in Transaction Amount (Q4 over Q1)
- `Total_Trans_Amt` : Total Transaction Amount (Last 12 months)
- `Total_Trans_Ct` : Total Transaction Count (Last 12 months)
- `Total_Ct_Chng_Q4_Q1` : Change in Transaction Count (Q4 over Q1)
- `Avg_Utilization_Ratio` : Average Card Utilization Ratio

## Exercise 4(a) (2 points)

Read the `Bank_Churners.csv` data-file and create a data-frame called `df`. Print the head of `df`.

In [66]:
import pandas as pd; pd.set_option('display.max_columns', None)
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import recall_score
from sklearn.linear_model import LogisticRegression

df = pd.read_csv('Bank_Churners.csv')
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

## Exercise 4(b) (2 points)

Map `Existing Customer` to 0 and `Attrited Customer` to 1.

In [67]:
df['Attrition_Flag'] = df['Attrition_Flag'].map({'Existing Customer': 0, 'Attrited Customer': 1})
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,0,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,0,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,0,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,0,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,0,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

## Exercise 4(c) (5 points)

Use `Customer_Age`, `Dependent_count`, `Months_on_book`, `Credit_Limit`, and `Total_Trans_Amt` as input features, and `Attrition_Flag` as the target feature. Split the data into `train (80%)` and `test (20%)`.

In [68]:
X = df[['Customer_Age', 'Dependent_count', 'Months_on_book', 'Credit_Limit', 'Total_Relationship_Count']].copy()
y = df['Attrition_Flag'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

## Exercise 4(d) (7 points)

Train and evaluate the `LogistRegression` model over 5-folds using the only the `train` dataset. Evalute the `recall` to evaluate model performance. Use 15% as threshold.

In [69]:
scores = []

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for  i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]
    
    model = LogisticRegression(max_iter=1000, random_state=42)
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict_proba(X_test_fold)[:,1]
    y_label = (y_pred >= 0.15).astype(int)
    recall = recall_score(y_test_fold, y_label)
    scores.append(recall)
    
    print(f'Fold {i+1}, Recall: {recall:.4f}')
    
print(f'Average recall over 5 folds: {np.mean(scores):.4f}')

Fold 1, Recall: 0.6552
Fold 2, Recall: 0.7308
Fold 3, Recall: 0.6846
Fold 4, Recall: 0.6269
Fold 5, Recall: 0.6207
Average recall over 5 folds: 0.6636

In [70]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

scores = []

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for  i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]
    
    model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000, random_state=42)) 
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict_proba(X_test_fold)[:,1]
    y_label = (y_pred >= 0.15).astype(int)
    recall = recall_score(y_test_fold, y_label)
    scores.append(recall)
    
    print(f'Fold {i+1}, Recall: {recall:.4f}')
    
print(f'Average recall over 5 folds: {np.mean(scores):.4f}')

Fold 1, Recall: 0.6552
Fold 2, Recall: 0.7308
Fold 3, Recall: 0.6885
Fold 4, Recall: 0.6269
Fold 5, Recall: 0.6207
Average recall over 5 folds: 0.6644

## Exercise 4(e) (7 points)

Train and evaluate the `DecisionTreeClassifier` model (use `max_depth=3`, `random_state=10`) over 5-folds using the only the `train` dataset. Evalute the `recall` to evaluate model performance. Use 15% as threshold.

In [71]:
from sklearn.tree import DecisionTreeClassifier
scores = []

for  i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]
    
    model = DecisionTreeClassifier(max_depth=3, random_state=10)
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict_proba(X_test_fold)[:,1]
    y_label = (y_pred >= 0.15).astype(int)
    recall = recall_score(y_test_fold, y_label)
    scores.append(recall)
    
    print(f'Fold {i+1}, Recall: {recall:.4f}')

print(f'Average recall over 5 folds: {np.mean(scores):.4f}')

Fold 1, Recall: 0.7088
Fold 2, Recall: 0.5538
Fold 3, Recall: 0.4808
Fold 4, Recall: 0.5115
Fold 5, Recall: 0.5096
Average recall over 5 folds: 0.5529

## Exercise 4(f) (2 points)

Based on the `recall`, what model would you use to predict `Attrition_Flag`?

Based on my results I would use the logistic regression with the standard scaler

## Exercise 4(g) (7 points)

Based on your answer from part 4(f), use that model to predict on the likely of `Attrition_Flag` on the `test` dataset.

In [73]:
test_pred = []

for  i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]
    
    model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000, random_state=42)) 
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict_proba(X_test)[:,1]
    test_pred.append(y_pred)
    
test = pd.concat([X_test.reset_index(drop=True),y_test.reset_index(drop=True)], axis=1)
test['predicted_attrition'] = np.mean(test_pred, axis=0)
test = test.sort_values(by='predicted_attrition', ascending=False).reset_index(drop=True)
test.head(10)

,Customer_Age,Dependent_count,Months_on_book,Credit_Limit,Total_Relationship_Count,Attrition_Flag,predicted_attrition
0,58,5,47,2038.0,1,0,0.353710
1,50,5,30,2033.0,1,0,0.351508
2,47,5,36,2761.0,1,0,0.336694
3,42,5,27,2437.0,1,0,0.334679
4,51,5,36,7645.0,1,0,0.332929
5,55,4,44,2638.0,1,0,0.332717
6,43,5,30,3092.0,1,0,0.332359
7,47,4,30,1438.3,1,0,0.330899
8,47,5,41,3429.0,1,0,0.330134
9,56,4,47,3426.0,1,0,0.330071