# Instructions

- Exam 1 is worth **148 points**. 
- Please strive for clarity and organization.
- **AI Usage**:
   - The use of AI is strictly **prohibited** for both conceptual and Python exercises.
- **Due Date: October 17, 2025, by 11:59 PM.**

# Exercise 1 (20 points) 

Please state **True** or **False** for the below statements.

- (a) Tokenization is the process of converting a sequence of text into smaller meaningful pieces like words or subwords.

- (b) In NLP, stemming involves reducing words to their base or root form, which might not always be a valid word. 

- (c) Bag-of-Words (BoW) model takes into account the order of words in a sentence while generating the vector representation of a text. 

- (d) Stop words are words that are filtered out before processing text data because they are considered less important for understanding the overall meaning of the text. 

- (e) Lemmatization and stemming both produce the same results by removing prefixes and suffixes from words. 

- (f) TF-IDF (Term Frequency-Inverse Document Frequency) is a technique used to reduce the dimensionality of text data by clustering words into topics. 

- (g) In NLP, unigram models consider one word at a time without any context from neighboring words, while bigram models consider pairs of words. 

- (h) Lemmatization always results in more accurate text cleaning compared to stemming because it reduces words to their actual dictionary form. 

- (i) Removing punctuation from text is a common text cleaning step in NLP to ensure better analysis of word patterns and meanings. 

- (j) In text cleaning, converting all text to lowercase is often done to avoid treating words like "Data" and "data" as different entities.

a. True

b. True

c. False

d. True

e. False

f. False

g. True

h. True

i. True

j. True

# Exercise 2 (5 points)

Suppose you are doing Bag-of-Words text classification ona document. The raw input is a single string containing the text of the entire document. In no more than three sentences, decribe the pipeline that you would consider to go from raw input to a feature vector.

The first step would be to clean the text by removing punctuation, stop words, and numbers. Next I would tokenize the text and lastly build the BoW model.

# Exercise 3 (4 points)

Which of the following is **not** a pre-processing technique in NLP?

- (a) Stemming and lemmatization
- (b) Converting to lowercase
- (c) Removing punctuations
- (d) Removal of stop words
- (e) Sentiment analysis
- (f) All of the above

E

# Exercise 4 (4 points)

What are some common challenges faced in NLP?

Some challenges are words with multiple meanings, noise in the data, and out of vocabulary words.

# Exercise 5 (4 points)

What is the purpose of word tokenizaion in the NLP pipeline?

- (a) Removing stop words
- (b) Removing pronouns
- (c) Removing emojis
- (d) Removing punctuation
- (e) Identifying parts of the text
- (f) Analyzing the text sentiment
- (g) Breaking the text into words or phrases
- (h) All of the above
- (i) None of the above

G

# Exercise 6 (10 points)

Given the following text,

```
text = "
Machine learning (ML) is a field of artificial intelligence. It's a key area in data science that deals with algorithms that help to predict a target variable. ML is all about tabular data! 
"
```

Clean `text` by 

- Converting all text to lowercase.
- Removing punctuation and special characters.
- Removing stop words.
- Tokenizing the text into words.

Create a function called `clean_text` that perform the above four bullet points. That is, your function structure should be as follows:

```
def clean_text(text):
    # 1. Convert to lowercase
    
    
    # 2. Remove punctuation and special characters
    
    
    # 3. Tokenize text into words
    
    
    # 4. Remove stop words
    
    return words
```

After the `clean_text` is applied to `text`. Report the top five most common words. Hint: you may consider using `Counter()` and `most_common()` to report the top five most common words. The answer should be:

```
[('ml', 2), ('data', 2), ('machine', 1), ('learning', 1), ('field', 1)]
```

In [1]:
import string
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "Machine learning (ML) is a field of artificial intelligence. It's a key area in data science that deals with algorithms that help to predict a target variable. ML is all about tabular data! "
stopwords = set(stopwords.words('english'))

def clean_text(text):
    # 1. Convert to lowercase
    text = text.lower()
    
    # 2. Remove punctuation and special characters
    text = ''.join([char for char in text if char not in string.punctuation])
    text = ''.join([char for char in text if char not in '“”‘’'])
    
    # 3. Tokenize text into words
    words = word_tokenize(text)
    
    # 4. Remove stop words
    words = [word for word in words if word not in stopwords]
    
    return words

text_clean = clean_text(text)
print(text_clean)

# top 5 most common words
from collections import Counter
word_counts = Counter(text_clean)
most_common_words = word_counts.most_common(5)
print(most_common_words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

['machine', 'learning', 'ml', 'field', 'artificial', 'intelligence', 'key', 'area', 'data', 'science', 'deals', 'algorithms', 'help', 'predict', 'target', 'variable', 'ml', 'tabular', 'data']
[('ml', 2), ('data', 2), ('machine', 1), ('learning', 1), ('field', 1)]

# Exercise 7 (4 points)

In Python's `NLTK` library, what function is used for tokenization?

- (a) `tokenize()`
- (b) `word_tokenize()`
- (c) `text_to_tokens()`
- (d) `split_to_tokens()`
- (e) None of the above

B

# Exercise 8 (4 points)

What are stop words, and why are they removed in text processing?

Stop words are words that don't have carry much meaningful information in the text such as 'the', 'in', 'of', 'and'. They are removed because they are common words that can overpower the other meaningful becasue they appear in the text more frequently.

# Exercise 9 (15 points)

You are given the following list of customer reviews:

```
reviews = [
    "The product is EXCELLENT!!! Very happy with the purchase.",
    "Worst service ever... I want my money back! #refund",
    "Good value for the price. Would recommend to anyone looking for affordable products.",
    "Mediocre quality, but fast delivery. Satisfied overall.",
    "Great product! Will buy again, definitely."
]
```

Write a Python function called `clean_reviews` that:

- Converts the text to lowercase.
- Removing punctuation and special characters.
- Remove stop words and pronouns.
- Removes numbers and special characters.
- Performs lemmatization on the text.
- Joins the cleaned words back into a single string.

Hint: see in-class assignment 6 for reference. The answer should be:

```
['product excellent happy purchase',
 'bad service ever want money back refund',
 'good value price would recommend anyone look affordable product',
 'mediocre quality fast delivery satisfied overall',
 'great product buy definitely']
```

In [2]:
import re
import string
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# download NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

reviews = [
    "The product is EXCELLENT!!! Very happy with the purchase.",
    "Worst service ever... I want my money back! #refund",
    "Good value for the price. Would recommend to anyone looking for affordable products.",
    "Mediocre quality, but fast delivery. Satisfied overall.",
    "Great product! Will buy again, definitely."
]

# funtion to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

# function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

pronouns = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves']

def clean_reviews(reviews):
    cleaned_reviews = []
    for review in reviews:
        # text to lower
        review = review.lower()
        # remove punctuation and special characters
        review = ''.join([char for char in review if char not in string.punctuation])
        review = ''.join([char for char in review if char not in '“”‘’'])
        # remove numbers
        review = remove_numbers(review)
        # tokenize
        words = word_tokenize(review)
        # remove stop words and pronouns
        words = [word for word in words if word not in stopwords and word not in pronouns]
        # perform lemmatization
        lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
        lemmatized_words = ' '.join(lemmatized_words)
        cleaned_reviews.append(lemmatized_words)
    return cleaned_reviews

cleaned_reviews = clean_reviews(reviews)
print(cleaned_reviews)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

['product excellent happy purchase', 'bad service ever want money back refund', 'good value price would recommend anyone look affordable product', 'mediocre quality fast delivery satisfied overall', 'great product buy definitely']

# Exercise 10 (4 points)

What is stemming in NLP?

- (a) Reducing words to their base or root form.
- (b) Assigning sentiment scores to words.
- (c) Analyzing grammatical structure.
- (d) Identifying name entities.
- (e) All of the above.
- (f) None of the above.

A

# Exercise 11 

Consider the `ecommerceDataset.csv`. This is an E-commerce text dataset for 4 categories - "Electronics", "Household", "Books" and "Clothing & Accessories", which almost cover 80% of any E-commerce website. The goal is build classification model to predict `Label`.

## Exercise 11(a) (2 points)

Read the datafile and create a data-frame called `df`.

In [3]:
import pandas as pd

df = pd.read_csv('ecommerceDataset.csv')
df.head()

       Label                                        Description
0  Household  Paper Plane Design Framed Wall Hanging Motivat...
1  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3  Household  SAF Flower Print Framed Painting (Synthetic, 1...
4  Household  Incredible Gifts India Wooden Happy Birthday U...

## Exercise 11(b) (2 points)

Report the proportion of the different labels stored in the `Label` column.

In [4]:
df.value_counts('Label', normalize=True)

Label
Household                 0.383004
Books                     0.234408
Electronics               0.210630
Clothing & Accessories    0.171958
Name: proportion, dtype: float64

## Exercise 11(c) (25 points)

Clean `Description` as follows:

- Remove punction using the `string` library
- Using the `nltk` library, remove stopwords, pronouns.
- Perform lemmatization 
- Remove any potential digits

Store the clean version of `Description` in a new column called `Description_clean`

In [5]:
import string
df['Description_clean'] = df['Description'].str.replace(f"[{string.punctuation}]", "", regex=True)
df.head()

,Label,Description,Description_clean
0,Household,Paper Plane Design Framed Wall Hanging Motivat...,Paper Plane Design Framed Wall Hanging Motivat...
1,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",SAF Floral Framed Painting Wood 30 inch x 10 i...
2,Household,SAF 'UV Textured Modern Art Print Framed' Pain...,SAF UV Textured Modern Art Print Framed Painti...
3,Household,"SAF Flower Print Framed Painting (Synthetic, 1...",SAF Flower Print Framed Painting Synthetic 135...
4,Household,Incredible Gifts India Wooden Happy Birthday U...,Incredible Gifts India Wooden Happy Birthday U...

In [6]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
pronouns = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves']

def clean_text(text):
    if not isinstance(text, str):
        return ""
    tokens = word_tokenize(text.lower())
    filtered_tokens = [word for word in tokens if word not in stop_words and word not in pronouns]
    return ' '.join(filtered_tokens)

df['Description_clean'] = df['Description_clean'].apply(clean_text)
df.head()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Label,Description,Description_clean
0,Household,Paper Plane Design Framed Wall Hanging Motivat...,paper plane design framed wall hanging motivat...
1,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",saf floral framed painting wood 30 inch x 10 i...
2,Household,SAF 'UV Textured Modern Art Print Framed' Pain...,saf uv textured modern art print framed painti...
3,Household,"SAF Flower Print Framed Painting (Synthetic, 1...",saf flower print framed painting synthetic 135...
4,Household,Incredible Gifts India Wooden Happy Birthday U...,incredible gifts india wooden happy birthday u...

In [7]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# download NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# funtion to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

df['Description_clean'] = df['Description_clean'].apply(lemmatize_text)
df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,Label,Description,Description_clean
0,Household,Paper Plane Design Framed Wall Hanging Motivat...,paper plane design frame wall hang motivationa...
1,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",saf floral frame painting wood 30 inch x 10 in...
2,Household,SAF 'UV Textured Modern Art Print Framed' Pain...,saf uv textured modern art print frame paintin...
3,Household,"SAF Flower Print Framed Painting (Synthetic, 1...",saf flower print frame painting synthetic 135 ...
4,Household,Incredible Gifts India Wooden Happy Birthday U...,incredible gift india wooden happy birthday un...

In [8]:
# function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

df['Description_clean'] = df['Description_clean'].apply(remove_numbers)
df.head()

,Label,Description,Description_clean
0,Household,Paper Plane Design Framed Wall Hanging Motivat...,paper plane design frame wall hang motivationa...
1,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",saf floral frame painting wood inch x inch s...
2,Household,SAF 'UV Textured Modern Art Print Framed' Pain...,saf uv textured modern art print frame paintin...
3,Household,"SAF Flower Print Framed Painting (Synthetic, 1...",saf flower print frame painting synthetic inc...
4,Household,Incredible Gifts India Wooden Happy Birthday U...,incredible gift india wooden happy birthday un...

## Exercise 11(d) (10 points)

Using the `TfidfVectorizer` function from `sklearn.feature_extraction.text`, convert the `Description_clean` column into matrix of token counts use `max_features=100` to create the input features, called this matrix `X`. Define `y = df['Label']`. Consider the following configuration:

```
tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)
```

Then, extract five topics using `LatentDirichletAllocation` with the following configuration:

```
# Initialize LDA with 4 topics
n_topics = 4
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    max_iter=100,
    learning_method='batch'
)
`

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)

# Fit and transform the cleaned text data
tfidf_matrix = tfidf_vectorizer.fit_transform(df['Description_clean'])

# Initialize LDA with 4 topics
n_topics = 4
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    max_iter=100,
    learning_method='batch'
)

# Fit the LDA model to the TF-IDF matrix
lda_topic_features = lda_model.fit_transform(tfidf_matrix)

In [10]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic {topic_idx}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))
        
no_top_words = 10
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
display_topics(lda_model, tfidf_feature_names, no_top_words)

Topic 0:
cotton set make wear fit fabric size look color soft
Topic 1:
book author men year india world life new work review
Topic 2:
use home cm easy light water make design camera plastic
Topic 3:
steel usb stainless power black cable device support mm card

## Exercise 11(e) (10 points)

Using the `TfidfVectorizer` function from `sklearn.feature_extraction.text`, convert the `Description_clean` column into matrix of token counts use `max_features=100` to create the input features, called this matrix `X`. Define `y = df['Label']`. Consider the following configuration:

```
tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)
```

Then, extract five topics using `NMF` with the following configuration:

```
# Initialize NMF with the same number of topics as LDA for comparison
nmf_model = NMF(
    n_components=n_topics,
    random_state=42,
    max_iter=200,
    alpha_W=0,    # Regularization parameter for W
    alpha_H=0,    # Regularization parameter for H
    l1_ratio=0.5    # Balance between L1 and L2 regularization
)
```

In [11]:
from sklearn.decomposition import NMF

nmf_model = NMF(
    n_components=n_topics,
    random_state=42,
    max_iter=200,
    alpha_W=0,    # Regularization parameter for W
    alpha_H=0,    # Regularization parameter for H
    l1_ratio=0.5    # Balance between L1 and L2 regularization
)

# Fit the NMF model to the TF-IDF matrix
nmf_topic_features = nmf_model.fit_transform(tfidf_matrix)

In [12]:
display_topics(nmf_model, tfidf_feature_names, no_top_words)

Topic 0:
use make set product design home easy steel quality color
Topic 1:
book author review life new world work year time india
Topic 2:
cotton men wear fit fabric print look soft pack make
Topic 3:
usb black power mm cable camera bluetooth device speaker audio

## Exercise 11(f) (10 points)

Generate topic features using K-means clustering on BERT embeddings. This approach:
1. Uses BERT to create dense semantic embeddings of the text
2. Applies K-means clustering to group similar documents (consider 4 clusters)
3. Creates features based on cluster assignments and distances

In [13]:
from sklearn.cluster import KMeans
from sentence_transformers import SentenceTransformer

print("loading BERT model...")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded.")

# Generate BERT embeddings for the cleaned text
print("Generating BERT embeddings...")
bert_embeddings = bert_model.encode(df['Description_clean'].tolist(), show_progress_bar=True, batch_size=32)

print(f'BERT embeddings shape: {bert_embeddings.shape}')
print(f'each document is represented by a {bert_embeddings.shape[1]}-dimensional vector')

loading BERT model...
Model loaded.
Generating BERT embeddings...

Batches:   0%|          | 0/1576 [00:00<?, ?it/s]

BERT embeddings shape: (50425, 384)
each document is represented by a 384-dimensional vector

In [14]:
import numpy as np
from sklearn.preprocessing import normalize

final_kmeans = KMeans(n_clusters=4, random_state=42, n_init=20)
cluster_labels = final_kmeans.fit_predict(normalize(bert_embeddings))

# feature 1: one-hot encoding of cluster labels
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)
cluster_labels_reshaped = cluster_labels.reshape(-1, 1)
cluster_onehot = onehot_encoder.fit_transform(cluster_labels_reshaped)

# feature 2: distance to cluster centroids
distances_to_centroids = final_kmeans.transform(normalize(bert_embeddings))

# feature 3: sofrmax probabilities based on distances
cluster_similarities = 1/(1+distances_to_centroids)
cluster_probabilities = cluster_similarities / cluster_similarities.sum(axis=1, keepdims=True)

print(f"cluster assignments shape: {cluster_onehot.shape}")
print(f"distances to centroids shape: {distances_to_centroids.shape}")
print(f"cluster probabilities shape: {cluster_probabilities.shape}")

# Combine all clustering features
X_cluster_features = np.hstack([cluster_onehot, distances_to_centroids, cluster_probabilities])
print(f"Combined clustering features shape: {X_cluster_features.shape}")

cluster assignments shape: (50425, 4)
distances to centroids shape: (50425, 4)
cluster probabilities shape: (50425, 4)
Combined clustering features shape: (50425, 12)

# Exercise 11(g) (15 points)

Train and evaluate three `LogisticRegression` models as follows:

- Using LDA features as input.
- Using NMF features as input.
- Combine LDA + NMF features as input.
- Bert cluster features.
- Bert embeddings.

Evaluate the five models over a five-fold cross validation strategy. Use the `accuracy` as measure of performance. Repor the performance of each of the models. What model would you use to predict `Label`?

In [15]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

y = df['Label'].map({'Household': 0, 'Books': 1, 'Electronics': 2, 'Clothing & Accessories': 3})
                     
X_1 = lda_topic_features
X_2 = nmf_topic_features
X_3 = np.hstack([X_1, X_2])  # Combine LDA and NMF features

print("Comparing model performance with different feature sets:")
print("==" * 50)

feature_sets = {
    'LDA': X_1,
    'NMF': X_2,
    'Combined': X_3,
    'BERT cluster features': X_cluster_features,
    'BERT embeddings': bert_embeddings
}

# Stratified Group K-Fold Cross-Validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=200))

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='accuracy', n_jobs=-1)
    results[name] = scores
    print(f"{name} Features: Mean Accuracy = {scores.mean():.4f}, Std = {scores.std():.4f}")
    print(f"Individual Fold Accuracies: {scores}")
    
# Identify the best feature set
best_feature_set = max(results, key=lambda k: results[k].mean())
print(f"\n Best Feature Set: {best_feature_set} with Mean Accuracy = {results[best_feature_set].mean():.4f}")

Comparing model performance with different feature sets:
====================================================================================================
LDA Features: Mean Accuracy = 0.6760, Std = 0.0078
Individual Fold Accuracies: [0.68150719 0.67724343 0.66960833 0.6650471  0.6865642 ]
NMF Features: Mean Accuracy = 0.7956, Std = 0.0031
Individual Fold Accuracies: [0.79871096 0.79464551 0.7909767  0.79424888 0.7993059 ]
Combined Features: Mean Accuracy = 0.8050, Std = 0.0029
Individual Fold Accuracies: [0.80912246 0.80495786 0.80059494 0.80337134 0.80704016]
BERT cluster features Features: Mean Accuracy = 0.8999, Std = 0.0036
Individual Fold Accuracies: [0.90133862 0.90342092 0.89776896 0.89390183 0.90292514]
BERT embeddings Features: Mean Accuracy = 0.9450, Std = 0.0012
Individual Fold Accuracies: [0.94586019 0.94566187 0.94457115 0.94278632 0.94615766]

 Best Feature Set: BERT embeddings with Mean Accuracy = 0.9450

I would use BERT embedding to predict Label since it had the highest accuracy