# Instructions

- This homework assignment is worth 61 points. 
- Please strive for clarity and organization.
- **AI Usage**:
   - AI use is strictly **prohibited** for conceptual exercises.
   - For applied (Python) exercises, you may only use AI for **debugging**. Do not use AI to generate answers.
- **Due Date: September 26, 2025, by 11:59 PM.**

# Exercise 1 

In this exercise, we will work with the `winemag-data-130k-v2.csv` data file. This file contains information about wine. The goal is to explore this data using the NLP techniques that we have learnt. For more information about the data file, see this [link](https://www.kaggle.com/datasets/zynicide/wine-reviews/data).

### Exercise 1(a) (2 points)

Load the following libraries as follows:

```
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
```

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `wine_df`.

In [3]:
wine_df = pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Exercise 1(c) (2 points)

Report the number of wine types in the `wine_df` data frame.

In [4]:
wine_df['variety'].nunique()

707

### Exercise 1(d) (2 points)

Report the number countries producing wine in the `wine_df` data frame.

In [5]:
wine_df['country'].nunique()

43

### Exercise 1(e) (3 points)

Using the `string` library, remove all the punctuation of the `description` column and store the results in another column called `description_clean`.

In [6]:
import string

wine_df['description_clean'] = wine_df['description'].str.replace(f"[]{string.punctuation}]", '', regex=True)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...

### Exercise 1(f) (10 points)

Using the `nltk` library, remove stopwords, pronouns, and the following words: `drink`, `now`, `wine`, `flavor`, and `flavors` from `description_clean` and store in another column called `'description_clean_1'`.

In [7]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stopwords = set(stopwords.words('english'))
pronouns = set(['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves'])
others = set(['drink', 'now', 'wine', 'flavor', 'flavors'])

def clean_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word not in stopwords and word not in pronouns and word not in others]
    return ' '.join(tokens)

wine_df['description_clean_1'] = wine_df['description_clean'].apply(clean_text)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...

### Exercise 1(g) (10 points)

Perform Lemmatization of `description_clean_1` and store the results in another column called `description_clean_2` in the `wine_df` data frame.

In [8]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# download NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# funtion to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

wine_df['description_clean_2'] = wine_df['description_clean_1'].apply(lemmatize_text)
wine_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...

### Exercise 1(h) (5 points)

Based on the results from part 1(g), we see digits in some of the text in `description_clean_2`. Remove all the digits from `description_clean_2` and store the results in another column `description_clean_3` in the `wine_df` data frame.

In [9]:
import re

# function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

wine_df['description_clean_3'] = wine_df['description_clean_2'].apply(remove_numbers)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2,description_clean_3
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...,aroma include tropical fruit broom brimstone d...
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...,ripe fruity smooth still structure firm tannin...
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...,much like regular bottle come across rather r...

### Exercise 1(i) (5 points)

Using the `CounterVectorizer` function from `sklearn.feature_extraction.text`, convert the `description_clean_3` column into matrix of token counts use `max_features=30` to create the input features, called this matrix `X`. Define `y = wine_df['points']`.

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

# initialize CountVectorizer with a maximum of 30 features
vectorizer = CountVectorizer(max_features=30)

# fit and transform the cleaned text data
X = vectorizer.fit_transform(wine_df['description_clean_3']).toarray()
y = wine_df['points']

### Exercise 1(j) (7 points)

Using 5-fold cross-validation strategy (use `KFold` from `sklearn.linear_model`), train and evaluate the out-of-sample performance of the `LinearRegression` model. Use `mean_squared_error` as measure of performance.

In [ ]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

# Initialize KFold
skf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = []
for i, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"Fold {i+1}")
    # Split the data
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Initialize and train the model
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # Make predictions and evaluate
    y_pred = model.predict(X_test)
    score = mean_squared_error(y_test, y_pred)
    scores.append(score)
    print(f"Fold MSE: {score}")
    
print(f"Average MSE: {np.mean(scores)}")

Fold 1
Fold MSE: 7.917786835548894
Fold 2
Fold MSE: 7.872728909752486
Fold 3
Fold MSE: 7.794458730524449
Fold 4
Fold MSE: 7.7407074641697315
Fold 5
Fold MSE: 7.854844914022021
Average MSE: 7.8361053708035175

### Exercise 1(k) (10 points)

Using the same cross-validation strategy from part 1(j), append `country` information to `X` as dummy columns (that is, use `get_dummies` from `pandas` to create dummy columns for `country`). Then, train and evaluate the out-of-fold performance of the `LinearRegression` model. Use `mean_squared_error` as measure of performance.

In [15]:
# Create dummy columns for 'country'
country_dummies = pd.get_dummies(wine_df['country'])

# Concatenate the original X and the dummy columns
X = np.hstack([X, country_dummies.values])
X

array([[1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
# Initialize KFold
skf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = []
for i, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"Fold {i+1}")
    # Split the data
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Initialize and train the model
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # Make predictions and evaluate
    y_pred = model.predict(X_test)
    score = mean_squared_error(y_test, y_pred)
    scores.append(score)
    print(f"Fold MSE: {score}")
    
print(f"Average MSE: {np.mean(scores)}")

Fold 1
Fold MSE: 7.475993109936517
Fold 2
Fold MSE: 7.418891891791852
Fold 3
Fold MSE: 7.3450607438091255
Fold 4
Fold MSE: 7.292533317595728
Fold 5
Fold MSE: 7.39824003886414
Average MSE: 7.3861438203994725

### Exercise 1(l) (3 points)

Based on the results from parts 1(j) and 1(k), what model would use to predict `score`? Please, be specific.

Based on my results I would use the model with the country data appended because it has the lowest MSE