# Instructions

- This homework assignment is worth 62 points. 
- Please strive for clarity and organization.
- **AI Usage**:
   - AI use is strictly **prohibited** for conceptual exercises.
   - For applied (Python) exercises, you may only use AI for **debugging**. Do not use AI to generate answers.
- **Due Date: October 31, 2025, by 11:59 PM.**

# Exercise 1 

In this exercise, we will work with the `winemag-data-130k-v2.csv` data file. This file contains information about wine. The goal is to explore this data using the NLP techniques that we have learnt. For more information about the data file, see this [link](https://www.kaggle.com/datasets/zynicide/wine-reviews/data).

### Exercise 1(a) (2 points)

Load the following libraries as follows:

```
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
```

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `wine_df`.

In [17]:
wine_df = pd.read_csv('winemag-data-130k-v2.csv')
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Exercise 1(c) (3 points)

Using the `string` library, remove all the punctuation of the `description` column and store the results in another column called `description_clean`.

In [18]:
import string

wine_df['description_clean'] = wine_df['description'].str.replace(f"[{string.punctuation}]", "", regex=True)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...

### Exercise 1(d) (10 points)

Using the `nltk` library, remove stopwords, pronouns, and the following words: `drink`, `now`, `wine`, `flavor`, and `flavors` from `description_clean` and store in another column called `'description_clean_1'`.

In [19]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stopwords = set(stopwords.words('english'))
pronouns = set(['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves'])
others = set(['drink', 'now', 'wine', 'flavor', 'flavors'])

def clean_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word not in stopwords and word not in pronouns and word not in others]
    return ' '.join(tokens)

wine_df['description_clean_1'] = wine_df['description_clean'].apply(clean_text)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...

### Exercise 1(e) (10 points)

Perform Lemmatization of `description_clean_1` and store the results in another column called `description_clean_2` in the `wine_df` data frame.

In [20]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# download NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# funtion to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

wine_df['description_clean_2'] = wine_df['description_clean_1'].apply(lemmatize_text)
wine_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...

### Exercise 1(f) (5 points)

Based on the results from part 1(g), we see digits in some of the text in `description_clean_2`. Remove all the digits from `description_clean_2` and store the results in another column `description_clean_3` in the `wine_df` data frame.

In [21]:
import re

# function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

wine_df['description_clean_3'] = wine_df['description_clean_2'].apply(remove_numbers)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2,description_clean_3
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...,aroma include tropical fruit broom brimstone d...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...,ripe fruity smooth still structure firm tannin...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...,much like regular bottle come across rather r...

### Exercise 1(g) (5 points)

Generate topic features using BERT embeddings on `description_clean_3`.

In [22]:
from sentence_transformers import SentenceTransformer

print("loading BERT model...")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded.")

# Generate BERT embeddings for the cleaned text
print("Generating BERT embeddings...")
bert_embeddings = bert_model.encode(wine_df['description_clean_3'].tolist(), show_progress_bar=True, batch_size=32)

print(f'BERT embeddings shape: {bert_embeddings.shape}')
print(f'each document is represented by a {bert_embeddings.shape[1]}-dimensional vector')

loading BERT model...
Model loaded.
Generating BERT embeddings...

Batches:   0%|          | 0/4062 [00:00<?, ?it/s]

BERT embeddings shape: (129971, 384)
each document is represented by a 384-dimensional vector

### Exercise 1(h) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=4.

2. Assign the cluster labels to a new column in `wine_df` called `'kmeans_cluster_label_4'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=4 clusters. Store these distances in a NumPy array called `X_kmeans_features_4`.

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Defining the KMeans model
kmeans_md = KMeans(n_clusters=4, n_init=20, random_state=42)

# Scaling the embeddings before clustering
scaler = StandardScaler()
bert_embeddings_scaled = scaler.fit_transform(bert_embeddings)

# Fitting the KMeans model
kmeans_md.fit(bert_embeddings_scaled)

# Getting cluster labels
cluster_labels = kmeans_md.labels_

# Assign cluster labels to original data
wine_df['kmeans_cluster_label_4'] = cluster_labels
print(wine_df[['description', 'kmeans_cluster_label_4']].head(10))

# Computing the distance of each point to each cluster center
X_kmeans_features_4 = kmeans_md.transform(bert_embeddings_scaled)

print(f"KMeans feature shape: {X_kmeans_features_4.shape}")

                                         description  kmeans_cluster_label_4
0  Aromas include tropical fruit, broom, brimston...                       1
1  This is ripe and fruity, a wine that is smooth...                       3
2  Tart and snappy, the flavors of lime flesh and...                       3
3  Pineapple rind, lemon pith and orange blossom ...                       1
4  Much like the regular bottling from 2012, this...                       2
5  Blackberry and raspberry aromas show a typical...                       0
6  Here's a bright, informal red that opens with ...                       0
7  This dry and restrained wine offers spice in p...                       1
8  Savory dried thyme notes accent sunnier flavor...                       1
9  This has great depth of flavor with its fresh ...                       3
KMeans feature shape: (129971, 4)

### Exercise 1(i) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=5.

2. Assign the cluster labels to a new column in `wine_df` called `'kmeans_cluster_label_5'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=4 clusters. Store these distances in a NumPy array called `X_kmeans_features_5`.

In [24]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Defining the KMeans model
kmeans_md = KMeans(n_clusters=5, n_init=20, random_state=42)

# Scaling the embeddings before clustering
scaler = StandardScaler()
bert_embeddings_scaled = scaler.fit_transform(bert_embeddings)

# Fitting the KMeans model
kmeans_md.fit(bert_embeddings_scaled)

# Getting cluster labels
cluster_labels = kmeans_md.labels_

# Assign cluster labels to original data
wine_df['kmeans_cluster_label_5'] = cluster_labels
print(wine_df[['description', 'kmeans_cluster_label_5']].head(10))

# Computing the distance of each point to each cluster center
X_kmeans_features_5 = kmeans_md.transform(bert_embeddings_scaled)

print(f"KMeans feature shape: {X_kmeans_features_5.shape}")

                                         description  kmeans_cluster_label_5
0  Aromas include tropical fruit, broom, brimston...                       1
1  This is ripe and fruity, a wine that is smooth...                       0
2  Tart and snappy, the flavors of lime flesh and...                       0
3  Pineapple rind, lemon pith and orange blossom ...                       3
4  Much like the regular bottling from 2012, this...                       2
5  Blackberry and raspberry aromas show a typical...                       1
6  Here's a bright, informal red that opens with ...                       1
7  This dry and restrained wine offers spice in p...                       3
8  Savory dried thyme notes accent sunnier flavor...                       3
9  This has great depth of flavor with its fresh ...                       0
KMeans feature shape: (129971, 5)

### Exercise 1(j) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=6.

2. Assign the cluster labels to a new column in `wine_df` called `'kmeans_cluster_label_6'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=4 clusters. Store these distances in a NumPy array called `X_kmeans_features_6`.

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Defining the KMeans model
kmeans_md = KMeans(n_clusters=6, n_init=20, random_state=42)

# Scaling the embeddings before clustering
scaler = StandardScaler()
bert_embeddings_scaled = scaler.fit_transform(bert_embeddings)

# Fitting the KMeans model
kmeans_md.fit(bert_embeddings_scaled)

# Getting cluster labels
cluster_labels = kmeans_md.labels_

# Assign cluster labels to original data
wine_df['kmeans_cluster_label_6'] = cluster_labels
print(wine_df[['description', 'kmeans_cluster_label_6']].head(10))

# Computing the distance of each point to each cluster center
X_kmeans_features_6 = kmeans_md.transform(bert_embeddings_scaled)

print(f"KMeans feature shape: {X_kmeans_features_6.shape}")

                                         description  kmeans_cluster_label_6
0  Aromas include tropical fruit, broom, brimston...                       2
1  This is ripe and fruity, a wine that is smooth...                       5
2  Tart and snappy, the flavors of lime flesh and...                       5
3  Pineapple rind, lemon pith and orange blossom ...                       1
4  Much like the regular bottling from 2012, this...                       3
5  Blackberry and raspberry aromas show a typical...                       2
6  Here's a bright, informal red that opens with ...                       2
7  This dry and restrained wine offers spice in p...                       1
8  Savory dried thyme notes accent sunnier flavor...                       1
9  This has great depth of flavor with its fresh ...                       5
KMeans feature shape: (129971, 6)

### Exercise 1(k) (10 points)

Train and evaluate (using `RMSE` as measure of performance) four `RandomForestRegressor` (with `n_estimators=100`, `max_depth=5`, and `random_state=42`) models as follows:

- Using `kmeans` (4 clusters) features as input.
- Using `kmeans` (5 clusters) features as input.
- Using `kmeans` (6 clusters) features as input.
- Comine `kmeans` (4 clusters) + `kmeans` (5 clusters) + `kmeans` (6 clusters) features as input.

Evaluate the four models over a five-fold cross validation strategy.

In [26]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

# Define the target variable
y = wine_df['points']

feature_sets = {
    'kmeans_4': X_kmeans_features_4,
    'kmeans_5': X_kmeans_features_5,
    'kmeans_6': X_kmeans_features_6,
    'kmeans_combined': np.hstack((X_kmeans_features_4, X_kmeans_features_5, X_kmeans_features_6))
}

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Train and evaluate Logistic Regression models
model = make_pipeline(StandardScaler(), RandomForestRegressor(n_estimators = 100, max_depth = 5, random_state=42))

results = {}
for name, x in feature_sets.items():
    scores = cross_val_score(model, x, y, cv=skf, scoring='neg_root_mean_squared_error') * -1
    results[name] = scores
    print(f"Model: {name} - RMSE: {np.mean(scores):.4f} ± {np.std(scores):.4f}")
    print(f"Individual fold scores: {scores}")
    
# Finding the best performing model
best_model = min(results, key=lambda k: np.mean(results[k]))
print(f"\n Best performing model: {best_model} with RMSE {np.mean(results[best_model]):.4f}")

Model: kmeans_4 - RMSE: 2.9027 ± 0.0059
Individual fold scores: [2.90577323 2.89297243 2.9103206  2.89983561 2.90466194]
Model: kmeans_5 - RMSE: 2.8996 ± 0.0050
Individual fold scores: [2.90461532 2.89059531 2.90139757 2.89815279 2.90332223]
Model: kmeans_6 - RMSE: 2.8607 ± 0.0044
Individual fold scores: [2.86607744 2.85516292 2.8637468  2.85598753 2.86275022]
Model: kmeans_combined - RMSE: 2.8575 ± 0.0043
Individual fold scores: [2.86247741 2.85111108 2.86075376 2.85395918 2.85923163]

 Best performing model: kmeans_combined with RMSE 2.8575