# Instructions

- This homework assignment is worth 89 points. 
- Please strive for clarity and organization.
- **AI Usage**:
   - AI use is strictly **prohibited** for conceptual exercises.
   - For applied (Python) exercises, you may only use AI for **debugging**. Do not use AI to generate answers.
- **Due Date: October 10, 2025, by 11:59 PM.**

# Exercise 1 

In this exercise, we will work with the `winemag-data-130k-v2.csv` data file. This file contains information about wine. The goal is to explore this data using the NLP techniques that we have learnt. For more information about the data file, see this [link](https://www.kaggle.com/datasets/zynicide/wine-reviews/data).

### Exercise 1(a) (2 points)

Load the following libraries as follows:

```
import pandas as pd 
import numpy as np
```

In [1]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `wine_df`.

In [2]:
wine_df = pd.read_csv('winemag-data-130k-v2.csv')
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Exercise 1(c) (2 points)

Report the number of wine types in the `wine_df` data frame.

In [4]:
wine_df['variety'].nunique()

707

### Exercise 1(d) (2 points)

Report the number countries producing wine in the `wine_df` data frame.

In [7]:
wine_df['country'].nunique()

43

### Exercise 1(e) (3 points)

Using the `string` library, remove all the punctuation of the `description` column and store the results in another column called `description_clean`.

In [8]:
import string

wine_df['description_clean'] = wine_df['description'].str.replace(f"[{string.punctuation}]", "", regex=True)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...

### Exercise 1(f) (10 points)

Using the `nltk` library, remove stopwords, pronouns, and the following words: `drink`, `now`, `wine`, `flavor`, and `flavors` from `description_clean` and store in another column called `'description_clean_1'`.

In [9]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stopwords = set(stopwords.words('english'))
pronouns = set(['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves'])
others = set(['drink', 'now', 'wine', 'flavor', 'flavors'])

def clean_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word not in stopwords and word not in pronouns and word not in others]
    return ' '.join(tokens)

wine_df['description_clean_1'] = wine_df['description_clean'].apply(clean_text)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...

### Exercise 1(g) (10 points)

Perform Lemmatization of `description_clean_1` and store the results in another column called `description_clean_2` in the `wine_df` data frame.

In [10]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# download NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# funtion to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

wine_df['description_clean_2'] = wine_df['description_clean_1'].apply(lemmatize_text)
wine_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\gmgma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...

### Exercise 1(h) (5 points)

Based on the results from part 1(g), we see digits in some of the text in `description_clean_2`. Remove all the digits from `description_clean_2` and store the results in another column `description_clean_3` in the `wine_df` data frame.

In [11]:
import re

# function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

wine_df['description_clean_3'] = wine_df['description_clean_2'].apply(remove_numbers)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2,description_clean_3
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aroma include tropical fruit broom brimstone d...,aroma include tropical fruit broom brimstone d...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structure firm tannin...,ripe fruity smooth still structure firm tannin...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottle 2012 come across rath...,much like regular bottle come across rather r...

### Exercise 1(i) (10 points)

Using the `TfidfVectorizer` function from `sklearn.feature_extraction.text`, convert the `description_clean_3` column into matrix of token counts use `max_features=100` to create the input features, called this matrix `X`. Define `y = wine_df['points']`. Consider the following configuration:

```
tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)
```

Then, extract five topics using `LatentDirichletAllocation` with the following configuration:

```
# Initialize LDA with 5 topics
n_topics = 5
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    max_iter=100,
    learning_method='batch'
)
```

Then, print the words associated to each of the topics.

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)

# Fit and transform the cleaned text data
tfidf_matrix = tfidf_vectorizer.fit_transform(wine_df['description_clean_3'])

print(f'TF-IDF matrix shape: {tfidf_matrix.shape}')
print(f'Number of features: {len(tfidf_vectorizer.get_feature_names_out())}')

# Initialize LDA with 5 topics
n_topics = 5
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    max_iter=100,
    learning_method='batch'
)

# Fit the LDA model to the TF-IDF matrix
lda_topic_features = lda_model.fit_transform(tfidf_matrix)

print(f'LDA topic features shape: {lda_topic_features.shape}')
print("each row represents a documents distribution over topics")

print('\n first 5 documents topic distribution:')
print(lda_topic_features[:5])

TF-IDF matrix shape: (129971, 100)
Number of features: 100
LDA topic features shape: (129971, 5)
each row represents a documents distribution over topics

 first 5 documents topic distribution:
[[0.05449302 0.05291342 0.05279462 0.05272243 0.78707652]
 [0.04801257 0.04753919 0.80984997 0.04733857 0.0472597 ]
 [0.06331829 0.06259997 0.0631688  0.06408677 0.74682618]
 [0.0579878  0.05710003 0.05641679 0.05883676 0.76965862]
 [0.53447758 0.05805123 0.05564358 0.29641696 0.05541065]]

In [14]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic {topic_idx}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))
        
no_top_words = 10
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
display_topics(lda_model, tfidf_feature_names, no_top_words)

Topic 0:
aroma palate cherry berry black plum finish tannin note red
Topic 1:
cabernet blackberry dark blend chocolate black merlot syrah sauvignon tannin
Topic 2:
fruit acidity age character ripe structure tannin rich wood fruity
Topic 3:
pinot taste like oak sweet raspberry cherry vanilla fruit finish
Topic 4:
apple citrus white lemon peach pear palate finish crisp fresh

### Exercise 1(j) (10 points)

Using the `TfidfVectorizer` function from `sklearn.feature_extraction.text`, convert the `description_clean_3` column into matrix of token counts use `max_features=100` to create the input features, called this matrix `X`. Define `y = wine_df['points']`. Consider the following configuration:

```
tfidf_vectorizer = TfidfVectorizer(
    max_features=100,
    max_df=0.8,  # Remove words that appear in more than 80% of documents
    min_df=5,    # Remove words that appear in fewer than 5 documents
    stop_words='english'
)
```

Then, extract five topics using `NMF` with the following configuration:

```
# Initialize NMF with the same number of topics as LDA for comparison
nmf_model = NMF(
    n_components=n_topics,
    random_state=42,
    max_iter=200,
    alpha_W=0,    # Regularization parameter for W
    alpha_H=0,    # Regularization parameter for H
    l1_ratio=0.5    # Balance between L1 and L2 regularization
)
```

In [15]:
from sklearn.decomposition import NMF

nmf_model = NMF(
    n_components=n_topics,
    random_state=42,
    max_iter=200,
    alpha_W=0,    # Regularization parameter for W
    alpha_H=0,    # Regularization parameter for H
    l1_ratio=0.5    # Balance between L1 and L2 regularization
)

# Fit the NMF model to the TF-IDF matrix
nmf_topic_features = nmf_model.fit_transform(tfidf_matrix)

print(f'NMF topic features shape: {nmf_topic_features.shape}')
print("each row represents a documents distribution over topics")

print('\n first 5 documents topic distribution:')
print(nmf_topic_features[:5])

NMF topic features shape: (129971, 5)
each row represents a documents distribution over topics

 first 5 documents topic distribution:
[[8.91127305e-03 4.24080664e-02 6.28399417e-03 1.60622984e-02
  0.00000000e+00]
 [0.00000000e+00 5.08863710e-03 6.18650682e-02 2.65365148e-02
  0.00000000e+00]
 [2.10173560e-04 4.78666984e-02 8.20414402e-05 0.00000000e+00
  0.00000000e+00]
 [2.23087075e-02 1.37273092e-02 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [5.53226234e-03 3.02456626e-04 7.62756158e-03 3.99359706e-03
  6.72229241e-03]]

In [16]:
display_topics(nmf_model, tfidf_feature_names, no_top_words)

Topic 0:
finish aroma palate note nose berry feel plum vanilla oak
Topic 1:
apple crisp acidity fresh citrus white lemon pear light peach
Topic 2:
fruit ripe rich age acidity structure tannin balance texture year
Topic 3:
cherry black tannin red dry pepper raspberry spice dark blackberry
Topic 4:
cabernet blend sauvignon merlot syrah blackberry oak chocolate make currant

### Exercise 1(k) (10 points)

Train and evaluate (using `RMSE` as measure of performance) three `LinearRegression` models as follows:

- Using LDA features as input.
- Using NMF features as input.
- Combine LDA + NMF features as input.

Evaluate the three models over a five-fold cross validation strategy.

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

y = wine_df['points']
X_1 = lda_topic_features
X_2 = nmf_topic_features
X_3 = np.hstack([X_1, X_2])  # Combine LDA and NMF features

print("Comparing model performance with different feature sets:")
print("==" * 50)

feature_sets = {
    'LDA': X_1,
    'NMF': X_2,
    'Combined': X_3
}

# K-Fold Cross-Validation
skf = KFold(n_splits=5, shuffle=True, random_state=42)
model = make_pipeline(StandardScaler(), LinearRegression())

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='neg_root_mean_squared_error', n_jobs=-1)
    rmse_scores = -scores  # Convert to positive RMSE
    results[name] = rmse_scores
    print(f"{name} Features: Mean RMSE = {rmse_scores.mean():.4f}, Std = {rmse_scores.std():.4f}")
    print(f"Individual Fold RMSE: {rmse_scores}")
    
# Identify the best feature set
best_feature_set = max(results, key=lambda k: results[k].mean())
print(f"\n Best Feature Set: {best_feature_set} with Mean RMSE = {results[best_feature_set].mean():.4f}")

Comparing model performance with different feature sets:
====================================================================================================
LDA Features: Mean RMSE = 2.9879, Std = 0.0103
Individual Fold RMSE: [3.00600793 2.98962628 2.98104269 2.97536244 2.98728855]
NMF Features: Mean RMSE = 2.9064, Std = 0.0115
Individual Fold RMSE: [2.92346067 2.91148071 2.89717023 2.89052516 2.90915988]
Combined Features: Mean RMSE = 2.8918, Std = 0.0121
Individual Fold RMSE: [2.90936335 2.89947915 2.8823621  2.87510394 2.89274961]

 Best Feature Set: LDA with Mean RMSE = 2.9879

### Exercise 1(l) (10 points)

Train and evaluate (using `RMSE` as measure of performance) three `RandomForestRegressor` (with `n_estimators=100`, and `max_depth=5`) models as follows:

- Using LDA features as input.
- Using NMF features as input.
- Combine LDA + NMF features as input.

Evaluate the three models over a five-fold cross validation strategy.

In [24]:
from sklearn.ensemble import RandomForestRegressor

print("Comparing model performance with different feature sets:")
print("==" * 50)

# K-Fold Cross-Validation
skf = KFold(n_splits=5, shuffle=True, random_state=42)
model = make_pipeline(StandardScaler(), RandomForestRegressor(n_estimators=100, max_depth=5))

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='neg_root_mean_squared_error', n_jobs=-1)
    rmse_scores = -scores  # Convert to positive RMSE
    results[name] = rmse_scores
    print(f"{name} Features: Mean RMSE = {rmse_scores.mean():.4f}, Std = {rmse_scores.std():.4f}")
    print(f"Individual Fold RMSE: {rmse_scores}")
    
# Identify the best feature set
best_feature_set = max(results, key=lambda k: results[k].mean())
print(f"\n Best Feature Set: {best_feature_set} with Mean RMSE = {results[best_feature_set].mean():.4f}")

Comparing model performance with different feature sets:
====================================================================================================
LDA Features: Mean RMSE = 2.7726, Std = 0.0094
Individual Fold RMSE: [2.78402666 2.78292615 2.76091459 2.77037163 2.76468933]
NMF Features: Mean RMSE = 2.8353, Std = 0.0122
Individual Fold RMSE: [2.84735314 2.84615184 2.82305956 2.81825829 2.84146085]
Combined Features: Mean RMSE = 2.6627, Std = 0.0096
Individual Fold RMSE: [2.6740678  2.67158306 2.64956868 2.65392487 2.66413734]

 Best Feature Set: NMF with Mean RMSE = 2.8353

### Exercise 1(m) (10 points)

Train and evaluate (using `RMSE` as measure of performance) three `SVR` (with `kernel='poly'`)models as follows:

- Using LDA features as input.
- Using NMF features as input.
- Combine LDA + NMF features as input.

Evaluate the three models over a five-fold cross validation strategy.

In [25]:
from sklearn.svm import SVR

print("Comparing model performance with different feature sets:")
print("==" * 50)

# K-Fold Cross-Validation
skf = KFold(n_splits=5, shuffle=True, random_state=42)
model = make_pipeline(StandardScaler(), SVR(kernel='poly'))

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='neg_root_mean_squared_error', n_jobs=-1)
    rmse_scores = -scores  # Convert to positive RMSE
    results[name] = rmse_scores
    print(f"{name} Features: Mean RMSE = {rmse_scores.mean():.4f}, Std = {rmse_scores.std():.4f}")
    print(f"Individual Fold RMSE: {rmse_scores}")
    
# Identify the best feature set
best_feature_set = max(results, key=lambda k: results[k].mean())
print(f"\n Best Feature Set: {best_feature_set} with Mean RMSE = {results[best_feature_set].mean():.4f}")

Comparing model performance with different feature sets:
====================================================================================================
LDA Features: Mean RMSE = 2.9864, Std = 0.0083
Individual Fold RMSE: [3.00171237 2.98669203 2.97842354 2.97963903 2.98558097]
NMF Features: Mean RMSE = 2.8986, Std = 0.0110
Individual Fold RMSE: [2.91033297 2.90498619 2.89377355 2.87942243 2.90436501]
Combined Features: Mean RMSE = 2.8489, Std = 0.0086
Individual Fold RMSE: [2.85426084 2.85892672 2.84357471 2.83503564 2.85291381]

 Best Feature Set: LDA with Mean RMSE = 2.9864

### Exercise 1(n) (3 points)

Based on the results from parts 1(k), 1(l) and 1(m), what model would use to predict `score`? Please, be specific.

Based on my results I would use the Random Forest model because it has the lowest RMSE